### ISSUE TITLE
Pin chart to integer axis labels for counter type

### ISSUE THREAD

**Issue by LostKobrakai** [mattludwigs/mobius#32]
We're using a counter metric, but the plot mobius prints uses floating point values for the y axis, which is a bit confusing:

```
2.00 ┤    ╭──  
1.92 ┤    │    
1.83 ┤    │    
1.75 ┤    │    
1.67 ┤    │    
1.58 ┤    │    
1.50 ┤    │    
1.42 ┤    │    
1.33 ┤    │    
1.25 ┤    │    
1.17 ┤    │    
1.08 ┼────╯    
```

This would be a jump from 1 -> 2.

**Comment by fhunleth** [comment]
@LostKobrakai We really, really, really want a better ASCII art charting library for Mobius. This one issue almost sounds fixable, but there are many issues. Matt and I have not had time to do a better ASCII charting library search or write one ourselves. If you know of any that we could switch to, I think that we'd be super grateful for this.
