### ISSUE TITLE
New user feedback

### ISSUE THREAD

**Issue by ewildgoose** [mattludwigs/mobius#39]
Hi, this is surely the wrong place, but I wonder if you might create a thread announcing your library on (say) elixirforum, so that people like myself can "send you requests to do free work in a better setting..." ;-)

OK, so I found your library recently. It's amazing! Very impressed. I guess the whole point is that I pondered adding some telemetry to an app, found myself with zero method to consume the data, short of spinning up Influx/Prometheus, etc, and so the default position becomes "what's the point?"  However your tiny timeseries database suddenly gives these metrics some life and accessibility - incredible!

OK, I found some rough spots. For sure I have a desire to turn these observations into pull requests, but between now and then perhaps the observations are interesting:

1) I'm not running on nerves, so I immediately hit a crash trying to start the app. The short version is it turned out to be the default data location (/data) wasn't available, but the error was very much unclear and in the end I needed to open up the code to figure out what I was doing wrong. (We simply need a wrapper around the ensure_mobius_persistence_path() call

2) The README references "Mobius.Charts.plot" however, I think this has changed to "Mobius.plot"?

3) Because i don't really understand creating telemetry (which isn't your problem), I had a hard time getting my first metric to plot.  Specifically:
- I didn't find a working example in the main readme. 
- I looked in your example dir, but I couldn't get my head around what was generating the metrics? (With the benefit of hindsight I think the user is supposed to use say iex, and run the functions?). I think I was blindsided that you have the telemetry_poller included and I was presuming it could invoke it somehow... New user blinkers is all
- I then checked hex docs and there is the example "Mobius.Charts.plot("vm.memory.total")", so changing this to the correct module and this looks like it uses the example from the Phoenix telemetry.ex module, so I paste in:
```
      summary("vm.memory.total", unit: {:byte, :kilobyte}),
```
Which doesn't work because it needs a Telemetry.Metrics in front of it, but it then still gives a very odd error due to the unit not being supported (I see #25, but I don't understand why the two things aren't equivalent?)
- I went around the houses for a bit because I think I ended up with both a "summary" and a "latest", and the error message when you try and plot because there are two series with the same name, wasn't clear to me, etc

Suggestion: Lets change the example metric in the docs to something that uses some real metrics that a new user can easily access, eg vm.memory.total

4) Related, but when I create a metric and use "tags: [:interface]", then don't specify a tag in the plot command it fails. However, the error isn't terribly clear that its related to multiple series and needing a tag, etc

5) Why can't we use the units conversion stuff? Are we not leveraging the whole of Telemetry.Metrics? Can we find a way to use it? Are other features unavailable like the filtering, etc?

6) Related, the Telemetry.Metrics stuff seems to assume that it's feeding into a Reporter, eg ConsoleReporter. Would it make sense to setup Mobius along these lines? Presumably this means the user would need to create a small telemetry summary module solely to feed into mobius, which could be different to the telemetry module you use in say phoenix?

7) I immediately wanted to show the graphing off in a LiveBook. It sorta works to use the console plot function, but really I want to get the raw data out so that I can draw a graph on a web page. Looking through the code I *think* this  could mean simply that we expose the "series_for_metric_from_metrics" as public? 

Feature request: Could we promote some function into the public interface which returns all the data needed to draw the graph, but in a form which can be re-used in other charting libraries? I think this basically means splitting the current Mobius.plot() into two and exposing the "series" variable it generates?

I think quite a few of the above are really small stuff and I could generate some PRs. But could you guide me a little? It's not totally clear where you see this library going? Also re the number 6, perhaps you could give a leg up on understanding the relationship with the Telemetry.Metrics for a new user like myself?

I would encourage you to post something on elixirforums - I would imagine with a little bit of orientation this will be a "ohh wow" kind of moment of enlightenment for a lot of people. At least for me it's transformed metrics from a theoretic use, to an actual useful, inspectable and touchable thing! Thanks!

**Comment by ewildgoose** [comment]
I've created a few PRs for some of the low hanging fixes above. Feedback appreciated?

**Comment by mattludwigs** [comment]
Hey @ewildgoose!

Thank you for your PRs and the feedback, I will look at them a bit more closely in the next few days or so.

### Running outside of a Nerves environment

This should be better documented, but in the example, we can pass in the `persistence_dir` option to Mobius: https://github.com/mattludwigs/mobius/blob/main/example/lib/example/application.ex#L22.

### Mobius Chart vs Mobius.plot

You're correct the README is currently wrong and should be `Mobius.plot`

### Telemetry

From experience, I say getting started with telemetry in Elixir land is a bit confusing - so maybe I can help.

There are three parts to a telemetry solution in Elixir:

1. The `telemetry` package
2. The `telemtry_metrics` package
3. A telemetry reporter

The telemetry package is rather lower-level and is responsible for sending events to some type of handler. The handler is a function that runs and accepts the event and does something with it.

The telemetry metrics package is more of a generic specification around telemetry events to give all Elixir projects a common language to handle telemetry data. 

A telemetry reporter is a module/library that implements a reporter according to the `:telemetry_metrics` reporter specification (https://hexdocs.pm/telemetry_metrics/writing_reporters.html#content). The role of this piece is to register a handle for the telemetry metrics and to process them. The difference between a reporter and base handler from the `telemetry` package is the reported understands the various `telemetry_metrics` structures. A base handler only processes raw telemetry events, a reporter processes telemetry metrics from the `telemetry_metrics` package.

Normally, a library will emit telemetry information. An example of such a library is `telemetry_poller`. All it does is send telemetry data every 1 second by default. It has some predefined telemetry events it sends out, but by default, it just sends out the data and does not care about who receives it. So, the example application uses `telemtry_poller` to get some base events reporting out to the telemetry library.

A reporter is normally used at the application level. So, a reporter can take a list of `telemetry_metrics` and will register a handler to `telemetry` and will process events. The reporter can do whatever, log to the console (https://hexdocs.pm/telemetry_metrics/Telemetry.Metrics.ConsoleReporter.html#content), send to a cloud-based observability tool, or save locally (Mobius does this). So you, as the application developer, can choose how you want the metrics reported. Ideally adding a reporter to an application should be mostly plug and play depending on where you want to send/store metrics.

The example project needs some updates and a bit of documentation but is mostly used to show how to configure Mobius. One thing with the example is to document how to use it. Which is to run `iex -S mix` and start calling the API Mobius exposes.

### Unit Conversion

Also, in regards to unit conversion (which I think you have a PR for that) in Mobius: we need to fix that up as it is outlined in the reporter speciation. Mobius does not currently meet that standard right now.

### API for getting time series for external plotting

I love this idea and the use case you present makes sense.

### Elixir forum

So, the main reason I haven't really pushed hard to announce Mobius (outside of Elixir conf) is that it is still experimental. It does the primary job it set out to do, store metrics locally, but as you pointed out can use a bit of useability work (APIs, documentation, etc). We use it in projects at SmartRent. Unfortunately, other priorities have pushed me off from giving much time to Mobius, but I hope to have some space to work on it soon. I like your ideas a lot and I am glad you are giving feedback to Mobius and making PRs. I would like to see this library be a viable localized metrics reporter, which means it should be well documented and have useful APIs. I don't mind breaking some of the APIs still as some of the plotting-related APIs are a bit much right now. I will definitely help guide you in your PRs and help you contribute to Mobius.


I appreciate your feedback and your effort to improve Mobius!

**Comment by ewildgoose** [comment]
I've tackled quite a few of these with some pull requests. Do you have any comments? Anything I can do to assist with a review?

**Comment by ewildgoose** [comment]
OK, I've also added a function to export the raw metrics data, so this now allows plotting it in Livebook with Vegalite. This is really cool!

The way I view Mobius is a mini timeseries database that I can use to aggregate up stuff quickly and get some visualisations. By timeseries I mean more RRD than InfluxDb... I've gone from not bothering with metrics to using them to do a bit of profiling on the dev of these patches (it's now so quick to check how many ms the save routine takes, etc! Amazing)

The filter function is now centralised and used across all functions that consume data. This provides the opportunity to expand this in the future, eg retrieving multi timeseries or whatever.

**Comment by mattludwigs** [comment]
Thanks for you all the issues and PRs, I am working on going through stuff today as I have time. Sorry for the delay, my family and I have been sick on top of some other high-priority work that I needed to get done. Thank you for your patience.

**Comment by ewildgoose** [comment]
I've posted a link to Mobius on elixirforum!

- https://elixirforum.com/t/mobius-mini-timeseries-database-esp-for-telemetry-more-rrd-than-influx

I've described Mobius as a simple RRD timeseries DB, and less as a plotting library. I hope it stimulates some interest!

**Comment by mattludwigs** [comment]
@ewildgoose that is awesome! Honestly, I didn't even know what an RRD was until you posted that, I am glad you were able to give concrete words to the implementation of Mobius.

The other good news is I have finally gotten some bandwidth to refocus on Mobius, so I will be able to get the PRs and open issues over the finish line.

Thank you for your continued support!

I missed the CFP for Empex Mountain but I should have submitted a talk for Mobius to that conference. Conference-driven development is a real motivator.

**Comment by mattludwigs** [comment]
@ewildgoose I am going to close this issue as it looks like you're in a good flow of submitting more specific issues and/or contributing to the project. Feel free to continue doing what you're doing. I appreciate your support, feedback, and contributions to the project!
